/* Copyright 2021 Glorious, LLC <salman@pcgamingrace.com>
   Copyright 2023 michael-mml

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "keycodes.h"
#include "modifiers.h"
#include "quantum_keycodes.h"
#include QMK_KEYBOARD_H
#include "def.h"
#include "layers.c"

/**
 * This file was generated by qmk json2c and edited to support the rotary
 * encoder and rgb.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    // clang-format off
    //      ESC      F1       F2       F3       F4       F5       F6       F7       F8       F9       F10      F11      F12	     Prt           Rotary(Mute)
    //
    //      ~        1        2        3        4        5        6        7        8        9        0         -       (=)	     BackSpc           Del
    //      Tab      Q        W        E        R        T        Y        U        I        O        P        [        ]        \                 PgUp
    //      Caps     A        S        D        F        G        H        J        K        L        ;        "                 Enter             PgDn
    //      Sh_L              Z        X        C        V        B        N        M        ,        .        ?                 Sh_R     Up       End
    //      Ct_L     Win_L    Alt_L                               SPACE                               Alt_R    FN       Ct_R     Left     Down     Right                                                                                                                                                           |92|
    //
    // RGB index codes corresponding to the keys above:
    // |67|  0,      6,       12,      18,      23,      28,      34,      39,      44,      50,      56,      61,      66,      69,               __,          |68|
    // |70|                                                                                                                                                     |71|
    // |73|  1,      7,       13,      19,      24,      29,      35,      40,      45,      51,      57,      62,      78,      85,               72,          |74|
    // |76|  2,      8,       14,      20,      25,      30,      36,      41,      46,      52,      58,      63,      89,      93,               75,          |77|
    // |80|  3,      9,       15,      21,      26,      31,      37,      42,      47,      53,      59,      64,               96,               86,          |81|
    // |83|  4,               10,      16,      22,      27,      32,      38,      43,      48,      54,      60,               90,      94,      82,          |84|
    // |87|  5,      11,      17,                                 33,                                 49,      55,      65,      95,      97,      79           |88|
    // |91|                                                                                                                                                     |92|
    // clang-format on

    // Holding the FN key on the default WIN layer toggles a Windows function layer which provides RGB controls, numpad,
    // and mouse keys (you can also tap the FN key once to momentenarily activate the function layer due to OSL; see
    // https://docs.qmk.fm/#/one_shot_keys).
    // In the Windows function layer, press 2 to switch to the MacOS layer where KC_LCTRL and KC_LALT are replaced with
    // KC_LGUI to simulate Windows.
    //
    // Holding the FN key on the MacOS layer toggles a MacOS function layer which provides the same RGB controls,
    // numpad, and mouse keys (you can also tap the FN key once to momentenarily activate the function layer due to OSL; see
    // https://docs.qmk.fm/#/one_shot_keys).
    // In the MacOS function layer, press 1 to switch to the Windows layer.
    //
    // To put the keyboard in bootloader mode, toggle any function layer by holding FN. Press \ to boot into bootloader.
    // If you accidentally put it into bootloader, you can just unplug the USB cable and it'll be back to normal when
    // you plug it back in.
    // Without this mapping, you have to open the case to hit the button on the bottom of the PCB (near the USB cable
    // attachment) while plugging in the USB cable to get the board into bootloader mode - definitely not fun when
    // you're working on your QMK builds. Remove this and put it back to KC_RGUI if that's your preference.
    //
    // This keyboard defaults to 6KRO instead of NKRO for compatibility reasons (some KVMs and BIOSes are incompatible
    // with NKRO).
    // Since this is, among other things, a "gaming" keyboard, a key combination to enable NKRO on the fly is provided
    // for convenience.
    // While in any function layer, press N to toggle between 6KRO and NKRO. This setting is persisted to the EEPROM and
    // thus persists between restarts.
    //
    // For convenience, modifier keys (e.g. KC_LCTRL) are OSMs. This means that clicking the modifier once will activate
    // it only for the next activated key. This is done to save keystrokes for common commands such as CTRL+C. See
    // https://docs.qmk.fm/#/one_shot_keys?id=one-shot-keys for examples.
    // clang-format off
    [WIN] = LAYOUT(
        KC_ESC,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,      KC_F11,   KC_F12,  KC_PSCR,          KC_MUTE,
        KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,        KC_MINS,  KC_EQL,  KC_BSPC,          KC_INS,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,        KC_LBRC,  KC_RBRC, KC_BSLS,          KC_DEL,
        KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN,     KC_QUOT,           KC_ENT,           KC_HOME,
        KC_LSFT,          KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,      KC_SLSH,           KC_RSFT, KC_UP,   KC_END,
        KC_LCTL, KC_LGUI, KC_LALT,                            KC_SPC,                    KC_RALT, OSL(WIN_FN),           KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT
    ),

    [WIN_FN] = LAYOUT(
        _______, KC_MYCM, KC_WHOM, KC_CALC, KC_MSEL, KC_MPRV, KC_MNXT, KC_MPLY, KC_MSTP, KC_MUTE, KC_VOLD,     KC_VOLU,  _______, _______,          RGB_TOG,
        _______, _______, DF(MAC), _______, _______, _______, _______, KC_NUM,  KC_PEQL, KC_PSLS, KC_PAST,     RGB_RMOD, RGB_MOD, _______,          KC_BTN1,
        _______, _______, RGB_HUI, _______, _______, _______, _______, KC_P7,   KC_P8,   KC_P9,   KC_PMNS,     _______,  _______, QK_BOOT,          KC_BTN2,
        _______, RGB_SPD, RGB_HUD, RGB_SPI, _______, _______, _______, KC_P4,   KC_P5,   KC_P6,   KC_PPLS,     _______,           _______,          KC_PGUP,
        _______,          _______, _______, _______, _______, NK_TOGG, _______, KC_P1,   KC_P2,   KC_P3,       KC_PDOT,           _______, KC_MS_U, KC_PGDN,
        _______, _______, _______,                            _______,                            KC_P0,       _______,  _______, KC_MS_L, KC_MS_D, KC_MS_R
    ),

    [MAC] = LAYOUT(
        KC_ESC,        KC_F1,         KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,        KC_F11,      KC_F12,        KC_PSCR,                KC_MUTE,
        KC_GRV,        KC_1,          KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,          KC_MINS,     KC_EQL,        KC_BSPC,                KC_INS,
        KC_TAB,        KC_Q,          KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,          KC_LBRC,     KC_RBRC,       KC_BSLS,                KC_DEL,
        KC_CAPS,       KC_A,          KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN,       KC_QUOT,                    KC_ENT,                 KC_HOME,
        OSM(MOD_LSFT),                KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,        KC_SLSH,                    OSM(MOD_RSFT), KC_UP,   KC_END,
        OSM(MOD_LGUI), OSM(MOD_LCTL), OSM(MOD_LGUI),                      KC_SPC,                             OSM(MOD_RALT), OSL(MAC_FN), OSM(MOD_RCTL), KC_LEFT,       KC_DOWN, KC_RGHT
    ),

    [MAC_FN] = LAYOUT(
        _______,       KC_MYCM,       KC_WHOM, KC_CALC, KC_MSEL, KC_MPRV, KC_MNXT, KC_MPLY, KC_MSTP, KC_MUTE, KC_VOLD,       KC_VOLU,    _______,        _______,                RGB_TOG,
        _______,       DF(WIN),       _______, _______, _______, _______, _______, KC_NUM,  KC_PEQL, KC_PSLS, KC_PAST,       RGB_RMOD,   RGB_MOD,        _______,                KC_BTN1,
        _______,       _______,       RGB_HUI, _______, _______, _______, _______, KC_P7,   KC_P8,   KC_P9,   KC_PMNS,       _______,    _______,        QK_BOOT,                KC_BTN2,
        _______,       RGB_SPD,       RGB_HUD, RGB_SPI, _______, _______, _______, KC_P4,   KC_P5,   KC_P6,   KC_PPLS,       _______,                    _______,                KC_PGUP,
        _______,                      _______, _______, _______, _______, NK_TOGG, _______, KC_P1  , KC_P2,   KC_P3,         KC_PDOT,                    _______,       KC_MS_U, KC_PGDN,
        _______,       _______,       _______,                            _______,                            KC_P0,         _______,    _______,        KC_MS_L,       KC_MS_D, KC_MS_R
    ),
    // clang-format on
};

// There are 2 flags set for enabling encoding; it is not clear which one is the correct one to enable.
// 1. https://github.com/qmk/qmk_firmware/blob/26b2288bde48659566809b2221a8e76bcd8dd20b/keyboards/gmmk/pro/rev1/ansi/rules.mk#L13
// 2. https://github.com/qmk/qmk_firmware/blob/26b2288bde48659566809b2221a8e76bcd8dd20b/keyboards/gmmk/pro/rev1/ansi/keymaps/default/rules.mk#L1
// ENCODER_MAP_ENABLE seems to be the more flexible mechanism, so prefer it over ENCODER_ENABLE
#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    // layer   // encoder 1
    [WIN]    = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU)},
    [WIN_FN] = {ENCODER_CCW_CW(RGB_VAD, RGB_VAI)},
    [MAC]    = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU)},
    [MAC_FN] = {ENCODER_CCW_CW(RGB_VAD, RGB_VAI)},
};
#endif

bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
    determine_rgb_per_layer(led_min, led_max);
    return true;
}

bool encoder_update_user(uint8_t index, bool clockwise) {
    return true;
}
